# Generated by Django 6.0 on 2025-12-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Müşteri'), ('business_owner', 'İşletme Sahibi'), ('staff', 'Personel')], default='customer', max_length=20),
        ),
    ]
