# Generated by Django 6.0 on 2025-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='table_type',
            field=models.CharField(blank=True, choices=[('2_person', '2 Kişilik Masa'), ('4_person', '4 Kişilik Masa')], max_length=20, null=True, verbose_name='Masa Tipi'),
        ),
    ]
